; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.24728.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ETenal\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
